
system:
  startup_app: "reactive_face"
  target_fps: 60
  ws_enabled: true
  transport: "udp://127.0.0.1:5555"

reactive_face:
  default_preset: "basic1"

video_player:
  default_video: rick.mp4
  
led_strip:
  led_number: 60
